services:
  nginx:
    image: nginx:1.25.1
    restart: always
    container_name: nginx
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf"
      - "./html/:/usr/share/nginx/html/"
      - "./logs/:/var/log/nginx/"
