services:
  sagoo-iot-open:
    image: sagoo-iot-open:1.0.3
    restart: always
    container_name: sagoo-iot-open
    build: 
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
      - redis
      - emqx
      - tdengine
    ports:
      - 8200:8200
    volumes:
      - "./resource/public/upload_file/:/opt/sagoo-iot-server/resource/public/upload_file"
      - "./resource/log/:/opt/sagoo-iot-server/resource/log"
